title:              Dan Santivañez
email:              dan.joshua.santivanez@gmail.com
description:        Blog personal
author:             Dan Santivañez Gutarra
baseurl:            ""
url:                "https://danjoshuasg.github.io"

# Social Profiles
twitter_username:   DanGutarra
github_username:    danjoshuasg
facebook_username:  Dan Santivañez Gutarra
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# bundle exec jekyll serve
